# frozen_string_literal: true
source "https://rubygems.org"

gem 'activerecord', '~> 5.0'
gem 'require_all'
gem 'sinatra-activerecord' # there some rake tasks in here that we will use
gem 'sqlite3'
gem 'rake'
gem 'pry'
